{"name": "Проверить, что вернется сообщение об ошибке при неверном пароле", "status": "passed", "start": 1723750640705, "stop": 1723750641050, "uuid": "2ad1bfd9-c321-471a-9801-806af757159b", "historyId": "b6e9e22f1544ec7bfb668dc27ba71b32", "testCaseId": "b6e9e22f1544ec7bfb668dc27ba71b32", "fullName": "tests.test_cuorier_login.TestCourierLogin#test_login_courier_incorrect_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_cuorier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "DESKTOP-C0DAUU0"}, {"name": "thread", "value": "13260-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_cuorier_login"}]}