{"name": "Проверить, что вернется сообщение об ошибке при неверном пароле", "status": "passed", "start": 1723488298859, "stop": 1723488299571, "uuid": "93264bf8-a60c-4e5e-8855-66873d4c5412", "historyId": "3cdb40d09ae83aeb611a6dfbd431bbef", "testCaseId": "3cdb40d09ae83aeb611a6dfbd431bbef", "fullName": "tests.test_cuorier_login#test_login_courier_incorrect_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_cuorier_login"}, {"name": "host", "value": "DESKTOP-C0DAUU0"}, {"name": "thread", "value": "15936-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_cuorier_login"}]}